- name: Tomcat deployment playbook
  hosts: webserver       
  become: yes               
  become_method: sudo       
  remote_user: ansible        
  vars:
    tomcat_ver: 9.0.64                          
    ui_manager_user: manager                    
    ui_manager_pass: manager01      
    ui_admin_username: admin                    
    ui_admin_pass: admin01          
  tasks:
    - include_tasks: redhat.yaml
      vars: 
        JAVA_HOME: /usr/lib/jvm/jre
      when: ansible_facts['os_family'] == "RedHat"
    - include_tasks: ubuntu.yaml
      vars:
        JAVA_HOME: /usr/lib/jvm/default-java
      when: ansible_facts['os_family'] == "Debian"